# Continuous integration configuration file, used by Jenkins
# Author: Chris Zalidis
install:
  - export ROS_DISTRO=hydro
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-catkin ros-$ROS_DISTRO-ros
  - sudo apt-get install -qq -y libgsl0-dev
  - sudo apt-get install -qq -y python-pip
  - sudo pip install pandoradep
  
  # Create workspace
  - mkdir -p $BUILD_HOME/catkin_ws/src
  - cd $BUILD_HOME/catkin_ws/src
  - rm -rf $BUILD_HOME/$REPOSITORY_NAME
  - wstool init .
  # Download non-debian stuff
  - wstool merge https://raw.github.com/pandora-auth-ros-pkg/install/hydro-devel/travis_ci.rosinstall
  - wstool update
  - cd ..
    
  - sudo rosdep init
  - rosdep update
  - rosdep install --from-paths src --ignore-src --rosdistro $ROS_DISTRO -y
  - source /opt/ros/$ROS_DISTRO/setup.bash
script: # All commands must exit with code 0 on success. Anything else is considered failure.
  - catkin_make
  - source devel/setup.bash
  - catkin_make roslint
  - catkin_make run_tests
  - catkin_test_results build
