controller_frequency: 5.0

base_local_planner: dwa_local_planner/DWAPlannerROS

DWAPlannerROS:
  # velocities
  max_trans_vel: 0.2
  min_trans_vel: 0.0

  max_vel_x: 0.2
  min_vel_x: -0.1

  max_vel_y: 0.0
  min_vel_y: 0.0

  max_rot_vel: 0.15
  min_rot_vel: 0.04

  # accel
  acc_lim_x: 1.3
  acc_lim_y: 0.0
  acc_lim_theta: 3.2
  acc_limit_trans: 1.3

  xy_goal_tolerance: 0.5
  yaw_goal_tolerance: 0.4
  latch_xy_goal_tolerance: true
  #DWA cfg
  vx_samples: 30
  vy_samples: 1
  vth_samples: 20

  path_distance_bias: 100.0
  use_dwa: true
  publish_cost_grid_pc: true
  publish_traj_pc: true
  cheat_factor: 2

