controller_frequency: 5.0

base_local_planner: dwa_local_planner/DWAPlannerROS

DWAPlannerROS:
  # velocities
  max_trans_vel: 0.15
  min_trans_vel: 0.0

  max_vel_x: 0.15
  min_vel_x: -0.1

  max_vel_y: 0.0
  min_vel_y: 0.0

  max_rot_vel: 0.3
  min_rot_vel: 0.01

  # accel
  acc_lim_x: 1.3
  acc_lim_y: 0.0
  acc_lim_theta: 3.2
  acc_limit_trans: 1.3

  xy_goal_tolerance: 0.3
  yaw_goal_tolerance: 0.3
  latch_xy_goal_tolerance: true
  #DWA cfg
  vx_samples: 10
  vy_samples: 1
  vth_samples: 30

  penalize_negative_x: true
  path_distance_bias: 100.0
  goal_distance_bias: 50.0
  occdist_scale: 0.4
  scaling_speed: 0.5
  prefer_forward_penalty: 80
  prefer_forward_scale: 60
  # def:0.01, how much the controller should attempt to avoid obstacles
  use_dwa: true
  publish_cost_grid_pc: true
  publish_traj_pc: true
  cheat_factor: 2
