global_costmap:
  global_frame: /map
  robot_base_frame: /base_footprint
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: true
  transform_tolerance: 0.5
  plugins:
    -
      name: static_layer
      type: costmap_2d::StaticLayer
    # -
    #   name: global_hard_layer
    #   type: costmap_2d::GlobalHardLayer
    -
      name: global_patch_layer
      type: costmap_2d::GlobalPatchLayer
    -
      name: inflation_layer
      type: costmap_2d::InflationLayer

  static_layer:
    map_topic: /slam/map
    unknown_cost_value: 51
    lethal_cost_threshold: 61
    subscribe_to_updates: false

  # global_hard_layer:
  #   map_topic: /vision/traversability_map
  #   unknown_cost_value: 51
  #   lethal_cost_threshold: 61


  global_patch_layer:
    map_topic: /map_patch/obstacles
    unknown_cost_value: 51
    lethal_cost_threshold: 61

  inflation_layer:
    inflation_radius: 0.6
    cost_scaling_factor: 7.0
