local_costmap:
  global_frame: /map
  robot_base_frame: /base_footprint
  update_frequency: 4.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution: 0.02
  transform_tolerance: 0.5
  track_unknown_space: false
  #robot_radius: 0.381
  plugins:
  -
   name: obstacle_layer
   type: costmap_2d::VoxelLayer
  -
   name: local_hard_layer
   type: costmap_2d::LocalHardLayer
  -
   name: local_soft_layer
   type: costmap_2d::LocalSoftLayer
  -
   name: inflation_layer
   type: costmap_2d::InflationLayer

  obstacle_layer:
    observation_sources: laser kinect sonar
    #observation_sources: laser
    laser: {data_type: LaserScan, topic: /laser/scan, marking: true, clearing: true}
    kinect: {data_type: PointCloud2, topic: /costmap/local_cropped_cloud, marking: true, clearing: true}
    sonar: {data_type: PointCloud2, topic: /sensors/range/point_cloud, marking: true, clearing: true}
    obstacle_range: 2.5
    raytrace_range: 3.0
    max_obstacle_height: 1.0
    publish_voxel_map: false

  local_hard_layer:
    global_hard_topic: /global_hard_layer/buffer_occupancy_grid
    unknown_cost_value: 51
    mitsos_cost_value: 50

  local_soft_layer:
    map_topic: /map_patch/obstacles
    unknown_cost_value: 51
    lethal_cost_threshold: 61

  inflation_layer:
    inflation_radius: 0.3
