local_costmap:
  global_frame: /map
  robot_base_frame: /base_footprint
  update_frequency: 4.0
  publish_frequency: 4.0
  static_map: false
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution: 0.02
  transform_tolerance: 0.5
  #robot_radius: 0.381
  plugins:
  - 
   name: obstacle_layer
   type: costmap_2d::VoxelLayer
  - 
   name: inflation_layer
   type: costmap_2d::InflationLayer

  obstacle_layer:
    # observation_sources: laser kinect
    observation_sources: laser
    laser: {data_type: LaserScan, topic: /laser/scan, marking: true, clearing: true}
    # kinect: {data_type: PointCloud2, topic: /costmap/local_cropped_cloud, marking: true, clearing: true}
    obstacle_range: 2.5
    raytrace_range: 3.0
    max_obstacle_height: 1.0
    publish_voxel_map: true

  inflation_layer:
    inflation_radius: 0.45

